### ISSUE TITLE
less 笔记

### ISSUE THREAD

**Issue by yulei521** [yulei521/my-blog#15]
### 方法

1、集合循环

```less
@pColos: red, blue, orange;

// @colors表示数组，@i从1开始
.colorForEach(@colors, @i: 1) when (@i <= length(@colors)) {
  // 根据索引获取对应数组值
  @color: extract(@colors, @i);
  // 字符串插值
  .color@{i} {
    background: @color;
  }
  // 循环遍历下一个
  .colorForEach(@colors, (@i + 1));
}

// 调用
.colorForEach(@pColos);
```
